-- Create a table for conversations
create table conversations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text not null default 'Nouvelle discussion',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for conversations
alter table conversations enable row level security;

create policy "Users can view their own conversations"
on conversations for select
using (auth.uid() = user_id);

create policy "Users can insert their own conversations"
on conversations for insert
with check (auth.uid() = user_id);

create policy "Users can delete their own conversations"
on conversations for delete
using (auth.uid() = user_id);

-- Re-create messages table with conversation_id
drop table if exists messages;

create table messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references conversations(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  content text check (char_length(content) > 0),
  is_ai boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for messages
alter table messages enable row level security;

create policy "Users can view their own messages"
on messages for select
using (auth.uid() = user_id);

create policy "Users can insert their own messages"
on messages for insert
with check (auth.uid() = user_id);
